[rocks]

[plugins]
"rocks.nvim" = "2.28.0"
"telescope.nvim" = "scm"
nvim-treesitter = "0.9.2"
"rocks-config.nvim" = "1.6.0"
"telescope-ui-select.nvim" = "scm"
"telescope-undo.nvim" = "scm"
"rocks-git.nvim" = "1.5.1"
"telescope-cmdline.nvim" = { git = "jonarrien/telescope-cmdline.nvim" }
"tokyonight.nvim" = "3.0.1"
neorg = "8.5.0"
neorg-telescope = "1.1.0"
"telescope-zf-native.nvim" = { git = "natecraddock/telescope-zf-native.nvim" }

[config]
plugins_dir = "plugins/"
auto_setup = false
