#!/usr/bin/env bash

[ ! -f ~/.eslint_d ] && eslint_d start
PORT=`cat ~/.eslint_d | cut -d" " -f1`
TOKEN=`cat ~/.eslint_d | cut -d" " -f2`

if [[ "$@" == *"--stdin"* ]]; then
  cat <(echo "$TOKEN $PWD $@") - | nc -q 0 localhost $PORT
else
  echo "$TOKEN $PWD $@" | nc -q 0 localhost $PORT
fi

