#!/usr/bin/env bash

[ ! -f ~/.prettier_d ] && prettier_d start
PORT=`cat ~/.prettier_d | cut -d" " -f1`
TOKEN=`cat ~/.prettier_d | cut -d" " -f2`

if [[ "$@" == *"--stdin"* ]]; then
  cat <(echo "$TOKEN $PWD $@") - | nc -q 0 localhost $PORT
else
  echo "$TOKEN $PWD $@" | nc -q 0 localhost $PORT
fi
